services:
  django:
    container_name: genologix-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
  
    

  db:
    container_name: genologix_mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      
    ports:
      - "3306:3306"
volumes:
  db_data:
