# Generated by Django 4.2.7 on 2023-12-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeartData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("sex", models.IntegerField()),
                ("cp", models.IntegerField()),
                ("trtbps", models.IntegerField()),
                ("chol", models.IntegerField()),
                ("fbs", models.IntegerField()),
                ("restecg", models.IntegerField()),
                ("thalachh", models.IntegerField()),
                ("exng", models.IntegerField()),
                ("oldpeak", models.FloatField()),
                ("slp", models.IntegerField()),
                ("caa", models.IntegerField()),
                ("thall", models.IntegerField()),
                ("prediction", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
